---
AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  InstanceTypeParameter:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - m1.small
      - m1.large
    Description: Enter t2.micro, m1.small, or m1.large. Default is t2.micro.
Resources:
  WebInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType:
        Ref: InstanceTypeParameter
      ImageId: ami-0742b4e673072066f
      KeyName: cf_ec2_keypair
      SecurityGroupIds:
        - sg_ec2_sales_test       
Outputs:
  MyWebInstanceID:
    Description: The Instance ID
    Value: !Ref WebInstance
  Status:
    Description: Stauts
    Value: "Very Good"
